services:
  db_postgres:
    container_name: udinus-postgres
    image: postgres:15.3
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_udinus_keycloak:/var/lib/postgres/data
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: udinus
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "9991:5432"
    networks:
      - local-network

  db_mysql:
    container_name: udinus-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: udinus
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    ports:
      - "9992:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - local-network

  keycloak:
    container_name: udinus-keycloak
    image: quay.io/keycloak/keycloak:21.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: udinus-postgres
      KC_DB_URL_DATABASE: db_keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: udinus
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: udinus
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "9993:8080"
    depends_on:
      db_postgres:
        condition: service_healthy
    networks:
      - local-network

  wordpress:
    container_name: udinus-wordpress
    image: wordpress
    restart: always
    ports:
      - "9994:80"
    environment:
      WORDPRESS_DB_HOST: db_mysql
      WORDPRESS_DB_USER: udinus
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db_wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - local-network

  odoo:
    container_name: udinus-odoo
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "9995:8069"
    networks:
      - local-network
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - local-network

  mariadb:
    container_name: udinus-mariadb
    image: bitnami/mariadb:latest
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: udinus
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: db_moodle
    ports:
      - "9998:3306"
    volumes:
      - "mariadb_data:/bitnami/mariadb"
      # - /path/to/mariadb-persistence:/bitnami/mariadb
    networks:
      - local-network
  moodle:
    container_name: udinus-moodle
    image: bitnami/moodle:latest
    ports:
      - "9996:8080"
      - "9999:8443"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MOODLE_DATABASE_USER: udinus
      MOODLE_DATABASE_PASSWORD: password
      MOODLE_DATABASE_NAME: db_moodle
    volumes:
      - "moodle_data:/bitnami/moodle"
      #  - /path/to/moodle-persistence:/bitnami/moodle
    networks:
      - local-network

volumes:
  pgdata_udinus_keycloak:
  data_mysql:
  wordpress:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
networks:
  local-network:
    driver: bridge